pricing_app/urls.py
from django.urls import path
from . import views 

app_name = 'pricing_app'

quote = [
    path('quote/', views.Quote.as_view(), name='quote'),
    path('pricing/', views.pricing, name='pricing'),
    path('download_template/', views.download_template_file, name='download_shipments_template'),
    path('download_sample/', views.download_sample_file, name='download_shipments_sample'),
    path('upload_file/', views.upload_file, name='upload_shipments_file'),
    path('upload_breakdown/<uuid:file_id>/', views.UploadBreakdown.as_view(), name='upload_breakdown'),
    path('download_shipments_with_pricing/<uuid:file_id>/', views.download_shipments_file_with_pricing, name='download_shipments_with_pricing'),
    path('about/', views.about, name='about'),
    path('create_rate_card/', views.CreateRateCardView.as_view(), name='create_rate_card'),
    path('rate_cards/', views.RateCardListView.as_view(), name='rate_cards'),
    path('rate_card/<uuid:rate_card_id>/', views.RateCardDetailView.as_view(), name='rate_card_detail'),
    path('create_rate_card_item_for/<uuid:rate_card_id>/', views.CreateRateCardItemView.as_view(), name='create_rate_card_item'),
    path('delete_rate_card_item/<uuid:rate_card_item_id>/<uuid:rate_card_id>/', views.DeleteRateCardItemView.as_view(), name='delete_rate_card_item'),
    path('', views.home, name='home'),
]


urlpatterns = [
   *quote,
]

users_app/urls.py
from django.urls import path, re_path
from .views import (ProfileView, OrderDetailView,
                    ShoppingCartView, ContactUsView,
                    add_to_cart,
                    email_terms_and_conditions,)


urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/order_detail/<uuid:file_id>/', OrderDetailView.as_view(), name='order_detail'),
    path('shopping_cart/', ShoppingCartView.as_view(), name='shopping_cart'),
    path('add_to_cart/<uuid:file_id>/', add_to_cart, name='add_to_cart'),
    path('contact_us/', ContactUsView.as_view(), name='contact_us'),
    path('email_terms_and_conditions/', email_terms_and_conditions, name='email_terms_and_conditions'),
]

templates/fragments/footer.html
<footer class=" bg-white rounded-lg shadow md:px-6 md:py-8 dark:bg-gray-900 border-solid border-t-2 border-gray-200 grow-0">
    <div class="sm:flex sm:items-center sm:justify-between">
        <a href="/" class="flex items-center mb-4 sm:mb-0">
              <img src="/static/images/allin1logo.png" class="h-6 mr-3 sm:h-9 mr-3" alt="Flowbite Logo" />
        </a>
        <div>
            <span class=" mt-2 block text-sm text-gray-500 sm:text-center dark:text-gray-400">Copyright © {% now "Y" %} AllinOneShip Inc. All Rights Reserved.
        </div>
        <ul class="flex flex-wrap items-center mb-6 text-sm text-gray-500 sm:mb-0 dark:text-gray-400">
            <li>
                <a href="{% url 'pricing_app:about'%}" class="mr-4 hover:underline md:mr-6 ">About</a>
            </li>
            <li>
                <a href="{% url 'contact_us' %}" class="hover:underline">Contact</a>
            </li>
            {% comment %} <li>
                <a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
            </li>
            <li>
                <a href="#" class="mr-4 hover:underline md:mr-6 ">Licensing</a>
            </li> {% endcomment %}
        </ul>
    </div>
    </span>
</footer>

templates/fragments/insurance_pricing_cards_fragment.html
<div class="flex items-stretch flex-wrap justify-center">
    <!-- Pricing Card -->
    <div class="flex flex-col p-6  max-w-lg m-3 items-center text-gray-900 bg-white rounded-lg border border-gray-100 shadow mt-14">
        <h3 class="mb-4 text-2xl font-semibold">Guest</h3>
        <p class="font-light text-gray-500 sm:text-lg dark:text-gray-400">Just Trying It Out, No account needed</p>
        <div class="flex justify-center items-baseline my-8">
            <span class="mr-2 text-5xl font-extrabold">$0.75</span>
            <span class="text-gray-500 dark:text-gray-400">/$100</span>
        </div>
        <!-- List -->
        <ul role="list" class="mb-8 space-y-4 text-left">
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Easy to insure</span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Seamless Claims</span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Good Pricing</span>
            </li>
            </li>
            <li class="flex items-center space-x-3 invisible">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>PH</span>
            </li>
            </li>
            <li class="flex items-center space-x-3 invisible">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>PH</span>
            </li>
        </ul>
        <a href="/#uploadFile" class="text-white w-1/2 mt-9 bg-blue-700 text-center hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5  dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Get Started</a>
    </div>
    <!-- Pricing Card -->
    <div class="flex flex-col p-6  max-w-lg m-3 items-center text-gray-900 bg-white rounded-lg border border-gray-100 shadow dark:border-gray-600 xl:p-8 dark:bg-gray-800 dark:text-white mt-14">
        <h3 class="mb-4 text-2xl font-semibold">Company</h3>
        <p class="font-light text-gray-500 sm:text-lg dark:text-gray-400">For small to medium size shippers</p>
        <div class="flex justify-center items-baseline my-8">
            <span class="mr-2 text-5xl font-extrabold">$0.53</span>
            <span class="text-gray-500 dark:text-gray-400" dark:text-gray-400>/$100</span>
        </div>
        <!-- List -->
        <ul role="list" class="mb-8 space-y-4 text-left">
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Easy to insure</span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Seamless Claims</span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Manage Your Account</span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Track All Your Order<span class="font-semibold"></span></span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Great Pricing</span>
            </li>
        </ul>
        <a title='create a account to get this rate'   href="{% url 'pricing_app:pricing' %}#valume_credit" class="text-white w-1/2 mt-9 bg-blue-700 text-center hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5  dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">More Info</a>
        {% comment %} {% if user.is_authenticated %}
        <a href="/#uploadFile" class="text-white w-1/2 mt-9 bg-blue-700 text-center hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5  dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Get Started</a>
        {% else %}
        <a title='create a account to get this rate'  href="{% url 'account_login' %}" class="text-white w-1/2 mt-9 bg-blue-700 text-center hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5  dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Get Started</a>
        {% endif %} {% endcomment %}
    </div>
    <!-- Pricing Card -->
    <div class="flex flex-col p-6 max-w-lg items-center m-3 text-gray-900 bg-white rounded-lg border border-gray-100 shadow dark:border-gray-600 xl:p-8 dark:bg-gray-800 dark:text-white mt-14">
        <h3 class="mb-4 text-2xl font-semibold">Enterprise</h3>
        <p class="font-light text-gray-500 sm:text-lg dark:text-gray-400">when insurance costs are obove ${{minimum_spend}} per month</p>
        <div class="flex justify-center items-baseline my-8">
            <span class="mr-2 text-5xl font-extrabold">$0.39</span>
            <span class="text-gray-500 dark:text-gray-400">/$100</span>
        </div>
        <!-- List -->
        <ul role="list" class="mb-8 space-y-4 text-left">
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Easy to insure</span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Seamless Claims</span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Manage Your Account</span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Track All Your Order<span class="font-semibold"></span></span>
            </li>
            <li class="flex items-center space-x-3">
                <!-- Icon -->
                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span>Best Pricing</span>
            </li>
        </ul>
        <a title='create a account to get this rate'  href="{% url 'pricing_app:pricing' %}#valume_credit" class="text-white w-1/2 mt-9 bg-blue-700 text-center hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5  dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">More Info</a>

    </div>
</div>

templates/fragments/shopping_cart_menu_link.html
  <a
                    href="{% url 'shopping_cart' %}"
                    id="shooping_cart"
                    class="block py-2 pl-3 pr-4border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-blue-500 md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700"
                >
                Cart
                <span
                class="smooth inline-flex items-center justify-center w-4 h-4 ml-2 text-xs font-semibold text-blue-800 bg-blue-400 rounded-full"
                >
                {{ cart_count }}
                </span>
                </a> 