pricing_app/urls.py
from django.urls import path
from . import views 

app_name = 'pricing_app'

quote = [
    path('quote/', views.Quote.as_view(), name='quote'),
    path('pricing/', views.pricing, name='pricing'),
    path('download_template/', views.download_template_file, name='download_shipments_template'),
    path('download_sample/', views.download_sample_file, name='download_shipments_sample'),
    path('upload_file/', views.upload_file, name='upload_shipments_file'),
    path('upload_breakdown/<uuid:file_id>/', views.UploadBreakdown.as_view(), name='upload_breakdown'),
    path('download_shipments_with_pricing/<uuid:file_id>/', views.download_shipments_file_with_pricing, name='download_shipments_with_pricing'),
    path('about/', views.about, name='about'),
    path('create_rate_card/', views.CreateRateCardView.as_view(), name='create_rate_card'),
    path('rate_cards/', views.RateCardListView.as_view(), name='rate_cards'),
    path('rate_card/<uuid:rate_card_id>/', views.RateCardDetailView.as_view(), name='rate_card_detail'),
    path('create_rate_card_item_for/<uuid:rate_card_id>/', views.CreateRateCardItemView.as_view(), name='create_rate_card_item'),
    path('delete_rate_card_item/<uuid:rate_card_item_id>/<uuid:rate_card_id>/', views.DeleteRateCardItemView.as_view(), name='delete_rate_card_item'),
    path('', views.home, name='home'),
]


urlpatterns = [
   *quote,
]

users_app/urls.py
from django.urls import path, re_path
from .views import (ProfileView, OrderDetailView,
                    ShoppingCartView, ContactUsView,
                    add_to_cart,
                    email_terms_and_conditions,)


urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/order_detail/<uuid:file_id>/', OrderDetailView.as_view(), name='order_detail'),
    path('shopping_cart/', ShoppingCartView.as_view(), name='shopping_cart'),
    path('add_to_cart/<uuid:file_id>/', add_to_cart, name='add_to_cart'),
    path('contact_us/', ContactUsView.as_view(), name='contact_us'),
    path('email_terms_and_conditions/', email_terms_and_conditions, name='email_terms_and_conditions'),
]

templates/base/base.html
{% load static %}
<html class="scroll-smooth">
  <head>
    <meta charset="utf-8">
    {% block css %}{% endblock css %}
    <title>{% block title %}Ship Secure{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/tailwind_output.css' %}">
  </head>

  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' class="flex flex-col h-screen justify-between">
    <header>
      {% include 'base/menu.html'%}
    </header>
   
    <main class="grow bg-gray-100">
     
      {% include  'includes/messages.html'%}
      {% block content %}
     
      {% endblock %}
    </main>
    
    {% include 'fragments/footer.html' %}
	{% include 'base/base_js_imports.html' %}
  </body>

</html>

templates/base/base_js_imports.html
{% load django_htmx %}
{% load static %}
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    <script src="{% static 'js/alpine.min.js' %}" defer></script>
    <script src="{% static 'flowbite/dist/flowbite.min.js' %}" defer></script>
    <script src="{% static 'flowbite/dist/datepicker.min.js' %}"></script>
    {% comment %} <script src="{% static 'js/base.js' %}" defer></script>  {% endcomment %}
{% django_htmx_script %}

templates/base/menu.html
{% load menue_tags %}

    <nav class="bg-white border-gray-200  border-solid border-b-2 px-2 md:px-4 py-2.5 grow-0">
        <div class="flex flex-wrap items-center justify-between max-w-screen-xl mx-auto ">
            <a href="/" class="flex items-center">
                <img src="/static/images/allin1logo.png" class="h-6 mr-3 sm:h-9" alt="Flowbite Logo" />
            </a>
            <div class="flex items-center md:order-2">
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'account_logout' %}" >
            {% csrf_token %}
                <button type='submit' class="text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 mr-1 md:mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">
                    Log Out
                </button>
            </form>
            {% else %}
            <a href="{% url 'account_login' %}" class="text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 mr-1 md:mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">Login</a>
            <a href="{% url 'account_signup' %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 mr-1 md:mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Sign up</a>
            {% endif %}
                <button data-collapse-toggle="mega-menu" type="button" class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mega-menu" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg aria-hidden="true" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
                </button>
            </div>
            <div id="mega-menu" class="items-center justify-between hidden w-full text-sm md:flex md:w-auto md:order-1">
                <ul class="flex flex-col mt-4 font-medium md:flex-row md:space-x-8 md:mt-0">
                {% if user.is_authenticated %}
              
            <li id="refreshed_cart">
                {% cart_count request as cart_count %}
                    <a
                        href="{% url 'shopping_cart' %}"
                        id="shooping_cart"
                        class="block py-2 pl-3 pr-4border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-blue-500 md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700"
                    >
                    Cart
                    <span
                    {% if cart_count > 0 %}
                        class="smooth inline-flex items-center justify-center w-4 h-4 ml-2 text-xs font-semibold text-blue-800 bg-blue-400 rounded-full"
                        {% else %}
                    class="hidden"
                    {% endif %}
                    >
                    {{ cart_count }}
                    </span>
                    </a> 
                </li>
                <li>
                    <a href="{% url 'profile' %}" class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-gray-400 md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700" >Profile</a>
                </li>
                    {% if user.is_superuser or user.is_staff %}
                    <li>
                        <a href="{% url 'admin_claim_list' %}" 
                        {% if 'claims' in request.path %}
                            class='text-orange-400'
                        {% else %}
                            class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-gray-400 md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700"
                        {% endif %}
                        >Claims</a>
                    </li>
                      <li>
                        <a href="{% url 'pricing_app:rate_cards' %}" 
                        {% if 'rate' in request.path %}
                        class='text-orange-400'
                        {% else %}
                        class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-gray-400 md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700"
                       {% endif %}
                        
                        >Rates</a>
                    </li>
                    {% endif %}
                {% endif %}
                    <li>
                        {% if request.path == '/' %}
                        <a href="#pricing_section" class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-gray-400 md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700">Pricing</a>
                        {% else %}
                        <a href="{% url 'pricing_app:pricing' %}" class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-gray-400 md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700">Pricing</a>
                        {% endif %}
                    </li>
               
                </ul>
            </div>
        </div>
    </nav>