payments_app/urls.py
from django.urls import path, re_path
from . import views 
from . import webhooks
# instantiate python date object with date 2000-01-01
# from datetime import date
# from django.utils import timezone
# from django.contrib.auth.decorators import login_required


 
app_name = 'payments_app'

process_payment = [
    path('checkout/<uuid:file_id>/', views.Checkout.as_view(), name='checkout'),
    # path('submit_order/', views.submit_order, name='submit_order'),
]

indirect_post_payment = [
    path('payment_complete/<uuid:order_id>/', views.payment_complete, name='payment_complete'),
    path('payment_canceled/<uuid:file_id>/', views.payment_canceled, name='payment_canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe_webhook'), # for stripe to tell us that a payment was successful or not
    # path('intuit/webhook/', webhooks.intuit_webhook, name='intuit_webhook'), # for intuit to tell us that a payment was successful or not
    # path('intuit_redirect/', views.intuit_redirect, name='intuit_redirect'), # this is a redirect url to send auth tokens
]


urlpatterns = [
   *process_payment,
   *indirect_post_payment,
]

pricing_app/urls.py
from django.urls import path
from . import views 

app_name = 'pricing_app'

quote = [
    path('quote/', views.Quote.as_view(), name='quote'),
    path('pricing/', views.pricing, name='pricing'),
    path('download_template/', views.download_template_file, name='download_shipments_template'),
    path('download_sample/', views.download_sample_file, name='download_shipments_sample'),
    path('upload_file/', views.upload_file, name='upload_shipments_file'),
    path('upload_breakdown/<uuid:file_id>/', views.UploadBreakdown.as_view(), name='upload_breakdown'),
    path('download_shipments_with_pricing/<uuid:file_id>/', views.download_shipments_file_with_pricing, name='download_shipments_with_pricing'),
    path('about/', views.about, name='about'),
    path('create_rate_card/', views.CreateRateCardView.as_view(), name='create_rate_card'),
    path('rate_cards/', views.RateCardListView.as_view(), name='rate_cards'),
    path('rate_card/<uuid:rate_card_id>/', views.RateCardDetailView.as_view(), name='rate_card_detail'),
    path('create_rate_card_item_for/<uuid:rate_card_id>/', views.CreateRateCardItemView.as_view(), name='create_rate_card_item'),
    path('delete_rate_card_item/<uuid:rate_card_item_id>/<uuid:rate_card_id>/', views.DeleteRateCardItemView.as_view(), name='delete_rate_card_item'),
    path('', views.home, name='home'),
]


urlpatterns = [
   *quote,
]

users_app/urls.py
from django.urls import path, re_path
from .views import (ProfileView, OrderDetailView,
                    ShoppingCartView, ContactUsView,
                    add_to_cart,
                    email_terms_and_conditions,)


urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/order_detail/<uuid:file_id>/', OrderDetailView.as_view(), name='order_detail'),
    path('shopping_cart/', ShoppingCartView.as_view(), name='shopping_cart'),
    path('add_to_cart/<uuid:file_id>/', add_to_cart, name='add_to_cart'),
    path('contact_us/', ContactUsView.as_view(), name='contact_us'),
    path('email_terms_and_conditions/', email_terms_and_conditions, name='email_terms_and_conditions'),
]

pricing_app/models.py
from django.core.validators import FileExtensionValidator
from utils.abstract_model import TimeStampedModel
from django.conf import settings
from django.db import models
import uuid

# model for storing shipments file. we treat this as a product model.
class ShipmentFile(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    file = models.FileField(upload_to='shipments_files/%Y/%m/%d', null=False, blank=False,
                            validators=[
                                FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])
                            ])
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='shipments_file', null=True, default=None)
    # if there is no user, store the ip address as a identifier
    ip_address = models.GenericIPAddressField(null=True, default=None)
    total_shipments = models.CharField(null=False, blank=True, max_length=255, default=0)
    price = models.DecimalField(max_digits=9, decimal_places=2, null=True,blank=True, default=None)
    description = models.TextField(null=True, blank=True)
    company_name = models.CharField(max_length=255, null=True, blank=True)
    in_cart = models.BooleanField(default=False)
    

    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return self.file.name
 
# models for Rate Cards
class RateCard(TimeStampedModel):
    TIER_CHOICES = (
        (1, 'Guest'),
        (2, 'Company'),
        (3, 'Enterprise'),
        (4, 'Custom') 
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tier_rank = models.PositiveIntegerField(null=False, blank=False, choices=TIER_CHOICES, default=1)
    minimum_spend = models.PositiveIntegerField(null=False, blank=False)
    affective_date = models.DateField(null=False, blank=False)
    expiration_date = models.DateField(null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='rate_card', null=True, default=None)
    

    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return self.description
    
    
# every shipment service gets its own RateCardItem (such as ups ground etc will get its own rateCardItem)
class RateCardItem(TimeStampedModel):
    CARRIER_CHOICES = (
        ('DHL eCommerce', 'DHL eCommerce'),
        ('DHL eCommerce International', 'DHL eCommerce International'),
        ('DHL Express Domestic', 'DHL Express Domestic'),
        ('DHL Express International', 'DHL Express International'),
        ('FedEx Domestic', 'FedEx Domestic'),
        ('FedEx International', 'FedEx International'),
        ('LaserShip Domestic', 'LaserShip Domestic'),
        ('UPS Domestic', 'UPS Domestic'),
        ('UPS International', 'UPS International'),
        ('UPS Domestic B to B', 'UPS Domestic B to B'),
        ('USPS Domestic', 'USPS Domestic'),
        ('USPS International', 'USPS International'),
    )
    
    PARCEL_LIMIT = (
        ('10000', '10000'),
        ('25000', '25000'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    rate_card = models.ForeignKey(RateCard, on_delete=models.CASCADE, null=False, blank=False)
    carrier = models.CharField(max_length=255, choices=CARRIER_CHOICES, null=False, blank=False)
    cost_per_DVU = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    parcel_limit_price_cap = models.DecimalField(max_digits=5, decimal_places=0,choices=PARCEL_LIMIT, null=False, blank=False)
    
    
    # add constraint to assure that there can only be unique carrier per rate_card
    # class Meta:
    #     unique_together = ('rate_card', 'carrier')
    
    def __str__(self):
        return self.carrier + ' - ' + str(self.cost_per_DVU)
    

pricing_app/views.py
import pandas as pd
from django.views.generic import View
from django.shortcuts import render, redirect, get_object_or_404
from .forms import FileUploadForm, CreateRateCardForm, CreateRateCardItemForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import ShipmentFile, RateCard, RateCardItem
from django.contrib import messages
from .services.uploaded_file_service import file_felid_validations, handle_file_upload
from utils.helper_functions import download_csv, download_csv_from_cloud
from django.contrib.auth.decorators import login_required
import random

class AdminOrStaff(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff
    
    
class Quote(View):
    def get(self, request):
        form = FileUploadForm()
        return render(request, "quote.html", {'form': form})

    def post(self, request):
        return render(request, "quote.html")

######## DOWNLOAD TEMPLATE FILE'S ########
def download_template_file(request):
    file_path = 'static/files/shipmentsTemplate.csv'
    return download_csv(file_path)

def download_sample_file(request):
    file_path = 'static/files/shipmentsSample.csv'
    return download_csv(file_path)

def download_shipments_file_with_pricing(request, file_id):
    file = get_object_or_404(ShipmentFile, id=file_id)
    return download_csv_from_cloud(file)


########### UPLOAD FILE OF SHIPMENTS TO GET A QUOTE ############
def upload_file(request):
    form = FileUploadForm(request.POST, request.FILES)
   
    if form.is_valid():
        file = form.cleaned_data['file']
        # update the file name to the file name plus a random string value before the file extension
        file.name = file.name.split('.')[0] + str(random.randint(1000, 9999)) + '.' + file.name.split('.')[1]
        file_or_error = file_felid_validations(request,file)
        # if the file is valid, then handle the file upload
        if isinstance(file_or_error ,list) == False: # if the file has no errors
            # call function from service to handle handle the actual file upload
            shipment = handle_file_upload(request, file)
            if not shipment:
                messages.error(request, 'Error Uploading file. Please contact customer support', extra_tags='alert')
                return redirect('pricing_app:quote')
            return redirect('pricing_app:upload_breakdown', str(shipment.id))
        
        # file has errors
        messages.error(request, file_or_error[0], extra_tags='alert')
        return redirect('pricing_app:home')
    
    
    # form not valid, message

    messages.error(request, form.errors['file'], extra_tags='alert')
    return redirect('pricing_app:home')

class UploadBreakdown(View):
    def get(self, request, file_id):
        file = get_object_or_404(ShipmentFile, id=file_id)
        DataFrame = pd.read_csv(file.file.url)
        # just in case error handling
        if DataFrame.empty:
            messages.error(request, 'File is empty', extra_tags='alert')
            return redirect('quote')
        else:
            total_price = DataFrame['Price'].sum()
            total_shipments = DataFrame.shape[0]

            try:
                file.price = total_price
                file.total_shipments = total_shipments
                file.save()
                
            except KeyError:
                messages.error(request, 'Please contact customer service ( error parsing Price colum )', extra_tags='alert')
                return redirect('quote')
            
            context = {'DataFrame': DataFrame, 'total_price': total_price, 'file_id': file_id, 'file_path': file.file, 'in_cart': file.in_cart}        
            return render(request, "shipments_breakdown.html", context)

    def post(self, request):
        return render(request, "shipments_breakdown.html")



class CreateRateCardView(View):
    def get(self, request):
        create_rate_card_form = CreateRateCardForm(can_edit_tier_rank=True)
        return render(request, "create_rate_card.html", {'create_rate_card_form': create_rate_card_form})

    def post(self, request):
        create_rate_card_form = CreateRateCardForm(request.POST, can_edit_tier_rank=True)
        if create_rate_card_form.is_valid():
            user = create_rate_card_form.cleaned_data['user']
            tier_rank = create_rate_card_form.cleaned_data['tier_rank']
            minimum_spend = create_rate_card_form.cleaned_data['minimum_spend']
            description = create_rate_card_form.cleaned_data['description']
            affective_date = create_rate_card_form.cleaned_data['affective_date']
            expiration_date = create_rate_card_form.cleaned_data['expiration_date']
            if user:
                rate_card = RateCard.objects.create(
                                description=description,
                                affective_date=affective_date,
                                expiration_date=expiration_date,
                                tier_rank=tier_rank,
                                minimum_spend=minimum_spend,
                                user=user,
                            )
            else:
                rate_card = RateCard.objects.create(
                                description=description,
                                affective_date=affective_date,
                                expiration_date=expiration_date,
                                tier_rank=tier_rank,
                                minimum_spend=minimum_spend,
                            )
                
            messages.success(request, 'Rate Card Created', extra_tags='alert')
            return redirect('pricing_app:rate_cards')
        messages.error(request, 'Error Creating Rate Card', extra_tags='alert')
        return render(request, "create_rate_card.html", {'create_rate_card_form': create_rate_card_form})
    
    

class RateCardDetailView(View):
    def get(self, request, rate_card_id):
        rate_card = get_object_or_404(RateCard, id=rate_card_id)
        rate_card_items = RateCardItem.objects.filter(rate_card=rate_card)
        create_rate_card_form = CreateRateCardForm(can_edit_tier_rank=False,
                                                   initial={
                                                       'description': rate_card.description,
                                                       'affective_date': rate_card.affective_date,
                                                       'expiration_date': rate_card.expiration_date,
                                                       'tier_rank': rate_card.tier_rank,
                                                       'minimum_spend': rate_card.minimum_spend,
                                                       'user': rate_card.user
                                                       }
                                                   )
        create_rate_card_item_form = CreateRateCardItemForm(rate_card=rate_card)
        return render(request, "rate_card_detail.html", {'rate_card': rate_card, 'create_rate_card_form': create_rate_card_form, 'create_rate_card_item_form': create_rate_card_item_form, 'rate_card_items': rate_card_items})

    def post(self, request, rate_card_id):
      
        if 'submit' in request.POST:
            # HANDLE POST REQUEST FROM THE UPDATE RATE CARD FORM
            create_rate_card_form = CreateRateCardForm(request.POST, can_edit_tier_rank=False)
            rate_card = get_object_or_404(RateCard, id=rate_card_id)
            if create_rate_card_form.is_valid():
                rate_card.description = create_rate_card_form.cleaned_data['description']
                rate_card.affective_date = create_rate_card_form.cleaned_data['affective_date']
                rate_card.expiration_date = create_rate_card_form.cleaned_data['expiration_date']
                rate_card.tier_rank = create_rate_card_form.cleaned_data['tier_rank']
                rate_card.minimum_spend = create_rate_card_form.cleaned_data['minimum_spend']
                if create_rate_card_form.cleaned_data['user']:
                    rate_card.user = create_rate_card_form.cleaned_data['user']
                rate_card.save()
                messages.success(request, 'Rate Card Updated', extra_tags='alert')
                return redirect('pricing_app:rate_cards')
            messages.error(request, 'Error Updating Rate Card', extra_tags='alert')
            return render(request, "rate_card_detail.html", {'rate_card': rate_card, 'create_rate_card_form': create_rate_card_form})
        elif 'delete' in request.POST:
            rate_card = get_object_or_404(RateCard, id=rate_card_id)
            rate_card.delete()
            messages.success(request, 'Rate Card Deleted', extra_tags='alert')
            return redirect('pricing_app:rate_cards')
    

class CreateRateCardItemView(AdminOrStaff):
    def post(self, request, rate_card_id):
        rate_card = get_object_or_404(RateCard, id=rate_card_id)
        create_rate_card_item_form = CreateRateCardItemForm(request.POST, rate_card=rate_card)
        if create_rate_card_item_form.is_valid():
            rate_card_item = RateCardItem.objects.create(
                                rate_card=rate_card,
                                carrier = create_rate_card_item_form.cleaned_data['carrier'],
                                cost_per_DVU = create_rate_card_item_form.cleaned_data['cost_per_DVU'],
                                parcel_limit_price_cap = create_rate_card_item_form.cleaned_data['parcel_limit_price_cap'],
                            )
            messages.success(request, 'Rate Card Item Created', extra_tags='alert')
            return redirect('pricing_app:rate_card_detail', rate_card_id=rate_card.id)
        messages.error(request, 'Error Creating Rate Card Item', extra_tags='alert')

pricing_app/templates/enterprise_insurance_quote.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Enterprise Quote{% endblock %}


{% block content %}
        <h1 class="text-center text-xl">Enterprise Quote Form Here</h1>
{% endblock content%}

pricing_app/templates/quote.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Get A Quote{% endblock %}



{% block content %}

    <h1>Welcome to allin1ship insurance offerings</h1>
    <h3>Download our template, Once the correct is fill out, Please Uplaod.</h3>
    <div class='download_spreadsheets'>
       
    <form action="{% url 'pricing_app:download_shipments_template' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Download Template">
    </form>

    <form action="{% url 'pricing_app:download_shipments_sample' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Download Sample File">
    </form>
</div>
    {% comment %} include file_upload.html {% endcomment %}
    {% include 'fragments/file_upload.html' %}
{% endblock %}

pricing_app/templates/rate_card_detail.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block title %}Rate Card Detail{% endblock %}

{% block content %}
<div class='flex flex-col justify-center items-center w-full'>
    {% comment %} THE ACTUAL RATE_CARD {% endcomment %}
    <form method="post" class='shadow-md p-6 rounded-lg w-5/6 mt-9' x-on:submit="disabledField = false" x-data=" {selectedOption: '{{create_rate_card_form.tier_rank.initial}}', disabledField: '{{create_rate_card_form.tier_rank.widget.attrs.disabled}}'} ">
        <h1 class="text-2xl font-bold text-gray-900">Rate Card Detail</h1>
        <h3 class="block mb-6 text-lg font-medium text-gray-900 underline text-center">{{page_header}}</h3>
        {% csrf_token %}
        {% include 'includes/form_errors.html' with errors=create_rate_card_form.non_field_errors %}
        <div class="grid gap-6 mb-6 md:grid-cols-2">
            <div>
                <label for="{{create_rate_card_form.tier_rank.id_for_label}}" class="block mb-2 text-sm font-medium text-gray-900">Tier</label>
                {% render_field create_rate_card_form.tier_rank x-model="selectedOption" x-bind::disabled="disabledField" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"%}
                {% include 'includes/form_errors.html' with errors=create_rate_card_form.tier_rank.errors %}
            </div>
            <div>
                <label for="{{create_rate_card_form.minimum_spend.id_for_label}}" class="block mb-2 text-sm font-medium text-gray-900">Minimum Spend Needed to qualify for tier</label>
                {% render_field create_rate_card_form.minimum_spend class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %}
                {% include 'includes/form_errors.html' with errors=create_rate_card_form.minimum_spend.errors %}
            </div>
            <div>
                <label for="{{create_rate_card_form.affective_date.id_for_label}}" class="block mb-2 text-sm font-medium text-gray-900">Effective Date</label>
                {% render_field create_rate_card_form.affective_date  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"  %}
                {% include 'includes/form_errors.html' with errors=create_rate_card_form.affective_date.errors %}
            </div>
            <div>
                <label for="{{create_rate_card_form.expiration_date.id_for_label}}" class="block mb-2 text-sm font-medium text-gray-900">Expiration Date</label>
                {% render_field create_rate_card_form.expiration_date  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"  %}
                {% include 'includes/form_errors.html' with errors=create_rate_card_form.expiration_date.errors %}
            </div>
            <div>
                <label for="{{create_rate_card_form.description.id_for_label}}" class="block mb-2 text-sm font-medium text-gray-900">Description</label>
                {% render_field create_rate_card_form.description  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" placeholder="write a brief description" %}
                {% include 'includes/form_errors.html' with errors=create_rate_card_form.description.errors %}
                {% include 'includes/form_errors.html' with errors=create_rate_card_form.description.errors %}
            </div>
            <div x-show=" selectedOption == '4' ">
                <label for="{{create_rate_card_form.user.id_for_label}}" class="block mb-2 text-sm font-medium text-gray-900">Select user for this Custome tier</label>
                {% render_field create_rate_card_form.user  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"%}
                {% include 'includes/form_errors.html' with errors=create_rate_card_form.user.errors %}
            </div>
        </div>
        <div class='flex justify-between'>
            <button type="submit" name='submit' class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Submit</button>
            <button type="submit" name='delete' class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">delete</button>
        </div>
    </form> 


    {% comment %} ADD A NEW CARRIER TO THE OBOVE RATE_CARD {% endcomment %}
  
  
    {% if create_rate_card_item_form.fields.carrier.choices|length > 0 %}
        <form method="post" action='{% url "pricing_app:create_rate_card_item" rate_card.id %}' class='shadow-md p-6 rounded-lg w-5/6 mt-9'>
            <h1 class="text-2xl font-bold text-gray-900">Add Shiping Service To The obove Rate Card</h1>
            <h3 class="block mb-6 text-lg font-medium text-gray-900 underline text-center">{{page_header}}</h3>
            {% csrf_token %}
            {% include 'includes/form_errors.html' with errors=create_rate_card_item_form.non_field_errors %}
            <div class="grid gap-6 mb-6 md:grid-cols-2">
                <div>
                    <label for="{{create_rate_card_item_form.carrier.id_for_label}}" class="block mb-2 text-sm font-medium text-gray-900">Carrier</label>
                    {% render_field create_rate_card_item_form.carrier class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"%}
                    {% include 'includes/form_errors.html' with errors=create_rate_card_item_form.carrier.errors %}
                </div>
                <div>
                    <label for="{{create_rate_card_item_form.cost_per_DVU.id_for_label}}" class="block mb-2 text-sm font-medium text-gray-900">cost per DVU</label>
                    {% render_field create_rate_card_item_form.cost_per_DVU class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %}
                    {% include 'includes/form_errors.html' with errors=create_rate_card_item_form.cost_per_DVU.errors %}
                </div>
                <div>
                    <label for="{{create_rate_card_item_form.parcel_limit_price_cap.id_for_label}}" class="block mb-2 text-sm font-medium text-gray-900">parcel limit price cap</label>
                    {% render_field create_rate_card_item_form.parcel_limit_price_cap  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"  %}
                    {% include 'includes/form_errors.html' with errors=create_rate_card_item_form.parcel_limit_price_cap.errors %}
                </div>
                
            </div>
            <div class='flex justify-between'>
                <button type="submit" name='submit' class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Submit</button>
            </div>
        </form> 
    {% endif %}

    {% comment %} A LIST OF ALL THE RATE CARD ITEMS ATTACHED TO THIS RATE CARD {% endcomment %}
     <h1 class="text-3xl font-bold text-gray-900 mt-10">Rate Card Services/Carriers</h1>
    <div class='shadow-md p-6 rounded-lg text-center flex flex-row flex-wrap justify-center w-5/6'>
        {% for rate_card_item in rate_card_items %}
            <div class="m-5 max-w-sm p-6 bg-gray-50  border border-gray-200 rounded-lg shadow ">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">Carrier: <span class="text-orange-400">{{ rate_card_item.carrier }}</span></h5>
                <h5 class="mb-2 text-1xl font-bold tracking-tight text-gray-700 ">Cost per DVU ${{rate_card_item.cost_per_DVU}}</h5>
                <h5 class="mb-2 text-1xl font-bold tracking-tight text-gray-700 ">Parcel limit Price Cap ${{rate_card_item.parcel_limit_price_cap}}</h5>
                <form method="post" action='{% url "pricing_app:delete_rate_card_item" rate_card_item.id rate_card.id %}' class='mb-0 mt-4'>
                    {% csrf_token %}
                    <button type="submit" name='delete' class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">delete</button>
                </form>
            </div>
        {% empty %}
            <h3 class="font-bold">No  Service Created yet</h3>
        {% endfor %}
    </div>
</div>
{% endblock content %}

pricing_app/templates/rate_card_list.html
{% extends 'base/base.html' %}

{% block title %}Rate Cards{% endblock %}

{% block content %}
<div class='flex flex-col justify-center items-center w-full mt-10'>

    <a href="{% url 'pricing_app:create_rate_card' %}" class="flex items-center align-middle justify-center  w-1/3 px-3 py-2 text-sm font-medium text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300">
        Create Now Rate Card
        <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </a>
    <h1 class="text-3xl font-bold text-gray-900 mt-10">Rate Cards</h1>
    <div class='shadow-md p-6 rounded-lg text-center flex flex-row flex-wrap justify-center w-5/6'>
        {% for rate_card in rate_cards %}
            <div class="m-5 max-w-sm p-6 bg-gray-50  border border-gray-200 rounded-lg shadow ">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">Tier Name: <span class="text-orange-400">{{ rate_card.get_tier_rank_display }}</span></h5>
                <p class="mb-3 font-normal text-gray-700 "><span class='font-bold'>Description:</span> {{rate_card.description}}</p>
                <h5 class="mb-2 text-1xl font-bold tracking-tight text-gray-700 ">Affective Date: {{rate_card.affective_date}}</h5>
                <h5 class="mb-2 text-1xl font-bold tracking-tight text-gray-700 ">Expiration Date: {{rate_card.expiration_date}}</h5>
                <h5 class="mb-2 text-1xl font-bold tracking-tight text-gray-700 ">Minimum Spend ${{rate_card.minimum_spend}}</h5>
                <a href="{% url 'pricing_app:rate_card_detail' rate_card.id %}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300">
                    Edit Rate Card
                    <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </a>
            </div>
        {% empty %}
            <h3 class="font-bold">No Claims found</h3>
        {% endfor %}
    </div>
</div>
{% endblock content %}